# Generated by Django 3.1.2 on 2020-10-24 14:46

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cracker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300, verbose_name='Cracker name')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=8, validators=[django.core.validators.MinValueValidator(limit_value=0)], verbose_name='Price')),
                ('pack_text', models.CharField(max_length=300, verbose_name='pack_text')),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300, verbose_name='Customer name')),
                ('phone_no', models.CharField(max_length=15, verbose_name='Phone number')),
            ],
        ),
        migrations.CreateModel(
            name='Sales',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_no', models.CharField(max_length=15, verbose_name='Invoice number')),
                ('date', models.DateTimeField(verbose_name='Sales date')),
                ('discount', models.DecimalField(decimal_places=2, default=0, max_digits=4, validators=[django.core.validators.MinValueValidator(limit_value=0)], verbose_name='Discount')),
                ('paid', models.DecimalField(decimal_places=2, default=0, max_digits=8, validators=[django.core.validators.MinValueValidator(limit_value=0)], verbose_name='Amount paid')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventoryman.customer')),
            ],
        ),
        migrations.CreateModel(
            name='SalesData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(limit_value=0)], verbose_name='Quantity')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventoryman.cracker')),
                ('sales_bill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventoryman.sales')),
            ],
        ),
    ]
