# Generated by Django 3.1.2 on 2020-11-05 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventoryman', '0002_auto_20201024_1451'),
    ]

    operations = [
        migrations.AddField(
            model_name='cracker',
            name='batch_number',
            field=models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='Batch number'),
        ),
        migrations.AddField(
            model_name='customer',
            name='email',
            field=models.EmailField(blank=True, default='', max_length=100, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='cracker',
            name='name',
            field=models.CharField(max_length=300, verbose_name='Cracker name'),
        ),
        migrations.AlterField(
            model_name='cracker',
            name='pack_text',
            field=models.CharField(choices=[('1', 'box'), ('2', 'pouch'), ('3', 'packet'), ('4', 'other')], default='4', max_length=50, verbose_name='pack_text'),
        ),
        migrations.AlterField(
            model_name='sales',
            name='invoice_no',
            field=models.CharField(max_length=15, unique=True, verbose_name='Invoice number'),
        ),
        migrations.AlterUniqueTogether(
            name='cracker',
            unique_together={('name', 'batch_number')},
        ),
    ]
