# Generated by Django 3.1.2 on 2020-11-07 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventoryman', '0003_auto_20201105_1428'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sales',
            name='invoice_no',
            field=models.CharField(max_length=100, unique=True, verbose_name='Invoice number'),
        ),
    ]
