module.exports = {
  GET_PRODUCTS: 'GET_PRODUCTS',
  FILTER_PRODUCTS: 'FILTER_PRODUCTS',
  ADD_PRODUCT: 'ADD_PRODUCT',
  UPDATE_PRODUCT: 'UPDATE_PRODUCT',
  GET_SALES: 'GET_SALES',
  GET_CUSTOMERS: 'GET_CUSTOMERS',
  SHOW_ERROR_TOAST: 'SHOW_ERROR_TOAST',
  SHOW_WARN_TOAST: 'SHOW_WARN_TOAST',
  SHOW_SUCCESS_TOAST: 'SHOW_SUCCESS_TOAST',
  SHOW_INFO_TOAST: 'SHOW_INFO_TOAST',
  HIDE_TOAST: 'HIDE_TOAST',
};
